### PR TITLE
Update setupTermuxArch.sh

### PR DESCRIPTION
**Pull request by ghost**
Replaced tar with bsdtar as it's the recommended option by archlinuxarm
Replaced instances of echo and empty echoes by printf and newlines
Autoremoves the files in case of md5 mismatch
Replaced mirror with os.archlinuxarm.org
Added more messages
Disabled verbose on wget and apt

### CODE REVIEW

**Comment by sdrausty** [comment]
Merge this pull request. 

This branch has conflicts that must be resolved.
Use the command line to resolve conflicts before continuing.

**Comment by sdrausty** [comment]
"This branch has no conflicts with the base branch.
Merging can be performed automatically.
We can’t automatically merge this pull request."

**Comment by sdrausty** [comment]
This branch was merged. https://github.com/sdrausty/TermuxArch/commit/1814fcdcc14a7295394d57090bcd9b8653539c99

**Comment by sdrausty** [comment]
Thank you for your contributions 😀

**Review by AYABULELA77 — APPROVED** [review]

**Pull request merged**
